# Generated by Django 4.1 on 2022-11-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minippa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='user_contact',
        ),
    ]
