# Generated by Django 4.1 on 2022-11-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minippa', '0002_rename_contact_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('decs', models.TextField()),
            ],
        ),
    ]
