# Generated by Django 4.1 on 2022-11-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minippa', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='decs',
            new_name='desc',
        ),
    ]
